### PR TITLE
Txt-contenttest-GT.md

### PR DESCRIPTION
**Pull request by gthurstonnz**
**This is a test of the instructions on how to add content.** 
But now I can use this tool to change the formatting so perhaps the layout template is not too relevent? 

We'll need those instructions on the best way to add content and how we treat it to ensure we have good accessability, for example the below PDF would not be acceptable.

[Empathy Map.pdf](https://github.com/ServiceInnovationLab/serviceinnovationlab.github.io/files/3449493/Empathy.Map.pdf)

### CODE REVIEW

**Comment by Br3nda** [comment]
I'm hoping to get percy hooked up to make this easier

**Comment by gthurstonnz** [comment]
Hi Jacob and Brenda. 
Please review and if good approve change. 
Because this is a test please let me know what steps I've missed to ensure the process I followed was robust. 
Cheers GT

**Comment by gthurstonnz** [comment]
> I'm hoping to get percy hooked up to make this easier

No Idea on what Percy is. How does percy make this easier?

**Comment by gthurstonnz** [comment]
> The github markdown formatting should be the same. Is there a link to the instruction? I should show while editing, and have a preview too

It does have a '.md' extension

**Comment by gthurstonnz** [comment]
> @gthurstonnz the file we pull down doesn't seem to have the .md extension. Have just created a PR for you to see how a markdown file should appear.
> 
> See #193

@JacOng17 I think I've got a bit lost. The instructions I wrote down with Dana obviously need a bit of work. Are you in tomorrow? Perhaps we can pick this up again in person.

**Comment by JacOng17** [comment]
@gthurstonnz Sure am! Will walk you through & can compare to my instructions. 

Check this out: https://github.com/ServiceInnovationLab/serviceinnovationlab.github.io/pull/192
Maybe it might help?

**Comment by gthurstonnz** [comment]
This was just a test and it served its purpose well. New instructions on publishing content is now in the readme for future test.

**Pull request closed without merging**
