### PR TITLE
Create exec-summary-ACC-betterrules-report.md

### PR DESCRIPTION
**Pull request by gthurstonnz**
I've used the summary from the ACC report and made it available to support the PDF version. The final report is going to be made accessable by GIS so I didn't want to replicate that work.

Please can you review etc

### CODE REVIEW

**Comment by JacOng17** [comment]
@gthurstonnz The file is placed in the wrong space...I suggest it should live under the Legislation as Code section. Will create a PR to address that & you can give your suggestions.

**Comment by JacOng17** [comment]
Created another PR to address this.

**Comment by mermop** [comment]
Is this closed by #253 ?

**Comment by JacOng17** [comment]
@mermop Yup

**Pull request closed without merging**
