### PR TITLE
uploaded a picture

### PR DESCRIPTION
**Pull request by romtoid**
added a picture of self for the testing

### CODE REVIEW

**Comment by Br3nda** [comment]
this image needs rotation 90 degrees clockwise -- also it's very very very large. Can it be shrunk?

**Comment by JacOng17** [comment]
@Br3nda Am on it. Have cropped & shrunk the image.

**Comment by Br3nda** [comment]
image
image
Looks good.
Merge when you're read @romtoid

**Comment by JacOng17** [comment]
@romtoid

**Pull request merged**
